# pull official base image
FROM node:14-buster-slim

# set working directory
WORKDIR /app 

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install

# add the web app
COPY . .

# start app
#CMD ["npm", "start"]
