version: "3.8"

services:
  web:
    container_name: web
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    command: npm start
    volumes:
      - ./frontend/src:/app/src

  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    volumes:
      - ./backend/:/backend/
    env_file:
      - ./backend/.env
    ports:
      - 8002:8000

  db:
    container_name: db
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    # expose:
    #  - 5432

    # For testing
    ports:
      - 5432:5432

volumes:
  postgres_data:
